POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json

{
  "ingredients": [
    {
      "id": 1,
      "amount": 10
    },
    {
      "id": 2,
      "amount": 20
    }
  ],
  "tags": [
    1,
    2
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "Нечто ",
  "text": "Приготовьте как нибудь эти ингредиеты",
  "cooking_time": 5
}

