MAX_LENGTH_NAME: int = 256

LENGTH_SHORT_TEXT: int = 40
LENGTH_LONG_TEXT: int = 80

INGREDIENT_LENGTH_NAME: int = 128
MEASUREMENT_UNIT_LENGTH: int = 64

MIN_COOKING_TIME: int = 1

REGEX_FIELD_SLUG = r'^[-a-zA-Z0-9_]+$'

MAX_LENGTH_TAG: int = 32

MAX_LENGTH_SLUG: int = 32

MIN_AMOUNT_SUM: int = 1

MAX_LENGTH_URL: int = 256
MIN_LENGTH_URL: int = 20
LIST_ON_PAGE = 10
SHORT_LINK_MAX_POSTFIX: int = 10
URL = 'https://<хост>.ddns.net/short/'
