MAX_LENGTH_NAME_FIELD: int = 55
MAX_LENGTH_SLUG: int = 90
MAX_LENGTH_NAME_INGREDIENTS: int = 150
MAX_LENGTH_UNIT: int = 45
MAX_LENGTH_NAME_RECIPE: int = 256
MIN_COOKING_TIME: int = 1
MIN_QUANTITY: int = 1
MAX_LENGTH_EMAIL: int = 254
MAX_LENGTH_USERNAME: int = 150
MAX_LENGTH_FIRST_NAME: int = 150
MAX_LENGTH_LAST_NAME: int = 150
MAX_LENGTH_SHORT_LINK: int = 30
REGEX_FIELD_USERNAME = r'^[\w.@+-]+\Z'

LIST_ON_PAGE: int = 7
