MAX_LENGTH_EMAIL: int = 254

MAX_LENGTH_USERNAME: int = 150
REGEX_FIELD_USERNAME = r'^[\w.@+-]+\Z'

MAX_LENGTH_FIRST_NAME: int = 150
MAX_LENGTH_LAST_NAME: int = 150

MIN_LENGTH_PASSWORD: int = 8
MAX_LENGTH_PASSWORD: int = 50

LENGTH_TEXT: int = 40

LIST_ON_PAGE: int = 5
