# Generated by Django 3.2.3 on 2025-02-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_shortlinkrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkrecipe',
            name='short_link',
            field=models.CharField(max_length=30, unique=True, verbose_name='Короткая ссылка рецепта'),
        ),
    ]
