# Generated by Django 3.2.3 on 2025-01-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите аватар пользователя.', upload_to='users/', verbose_name='Аватар'),
        ),
    ]
