# Generated by Django 3.2.3 on 2025-02-01 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('username', 'last_name'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Юзернейм должно быть уникальным.', max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Юзернейм содержит недопустимый символ. Только буквы, цифры и @/./+/-/_.', regex='^[\\w.@+-]+\\Z')], verbose_name='Уникальный юзернейм'),
        ),
    ]
