# Generated by Django 3.2.3 on 2025-02-01 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250201_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=1, help_text='Юзернейм должно быть уникальным.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Юзернейм содержит недопустимый символ. Только буквы, цифры и @/./+/-/_.', regex='^[\\w.@+-]+\\Z')], verbose_name='Уникальный юзернейм'),
            preserve_default=False,
        ),
    ]
